run:
  timeout: 3m
  issues-exit-code: 1

linters:
  enable-all: false  # Explicitly disable all linters except those listed below.
  enable:
    - govet
    - gofmt
    - goimports
    - revive
    - errcheck  # Ensure all errors are checked in the code.